//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6TempTableKit.UnitTest.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSalesPersonSalesByFiscalYear
    {
        public Nullable<int> SalesPersonID { get; set; }
        public string FullName { get; set; }
        public string JobTitle { get; set; }
        public string SalesTerritory { get; set; }
        public Nullable<decimal> C2002 { get; set; }
        public Nullable<decimal> C2003 { get; set; }
        public Nullable<decimal> C2004 { get; set; }
    }
}
