//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6TempTableKit.Test.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStoreWithDemographic
    {
        public int BusinessEntityID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> AnnualSales { get; set; }
        public Nullable<decimal> AnnualRevenue { get; set; }
        public string BankName { get; set; }
        public string BusinessType { get; set; }
        public Nullable<int> YearOpened { get; set; }
        public string Specialty { get; set; }
        public Nullable<int> SquareFeet { get; set; }
        public string Brands { get; set; }
        public string Internet { get; set; }
        public Nullable<int> NumberEmployees { get; set; }
    }
}
