//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIntercept.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class AdventureWorksDW2008R2Entities : DbContextExtended
    {
        public AdventureWorksDW2008R2Entities()
            : base("name=AdventureWorksDW2008R2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimReseller> DimReseller { get; set; }
    }

    [DbConfigurationType(typeof(DbConfig))]
    public partial class AdventureWorksDW2008R2EntitiesCustomized : AdventureWorksDW2008R2Entities
    {
        //public Func<AdventureWorksDW2008R2EntitiesCustomized, string, string> Method { get; set; }

        //public AdventureWorksDW2008R2EntitiesCustomized WithCustomQuery(Func<AdventureWorksDW2008R2EntitiesCustomized, string, string> method)
        //{
        //    Method = method;

        //    return this;
        //}
    }


    [DbConfigurationType(typeof(DbConfig))]
    public partial class DbContextExtended : DbContext
    {
        public DbContextExtended(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }

        public Func<DbContextExtended, string, string> Method { get; set; }
    }
}
