using System.Collections.Generic;
using System.Data.Common;
using System.Data.Entity.Infrastructure.Interception;

namespace EF6TempTableKit.DbContext
{
    public sealed class EF6TempTableKitQueryInterceptor : DbCommandInterceptor
    {
        public override void ReaderExecuting(DbCommand command, DbCommandInterceptionContext<DbDataReader> interceptionContext)
        {
            PrependTempTableSql(command, interceptionContext);
        }

        private void PrependTempTableSql<T>(DbCommand command, DbCommandInterceptionContext<T> interceptionContext)
        {
            var dbContextWithTempTable = FindDbContextWithTempTable(interceptionContext.DbContexts);
            if (dbContextWithTempTable != null && ((IDbContextWithTempTable) dbContextWithTempTable)?.TempTableContainer?.TempSqlQueriesList?.Count > 0)
            {
                var currentCommandText = command.CommandText;
                var selectCommandText = "";
                var assemblyVersion = typeof(EF6TempTableKitQueryInterceptor).Assembly.GetName().Version;
                var generatedByEf6TempTableKitStartMsg = $"/* Generated by EF6TempTableKit {assemblyVersion} - START */";
                var generatedByEf6TempTableKitEndMsg = $"/* Generated by EF6TempTableKit {assemblyVersion} - END*/";
                var contextWithTempTable = (IDbContextWithTempTable)dbContextWithTempTable;
                foreach (var sqlTempQuery in contextWithTempTable.TempTableContainer.TempSqlQueriesList)
                {
                    if (sqlTempQuery.Value.ReuseExisting)
                    {
                        dbContextWithTempTable.Database.ExecuteSqlCommand(
                                generatedByEf6TempTableKitStartMsg
                                + "\n"
                                + sqlTempQuery.Value.QueryString
                                + "\n"
                                + generatedByEf6TempTableKitEndMsg
                            );
                    }
                    else
                    {
                        if (command.CommandText.Contains(sqlTempQuery.Key))
                        {
                            selectCommandText =
                                "\n" 
                                + generatedByEf6TempTableKitStartMsg
                                + "\n"
                                + sqlTempQuery.Value.QueryString
                                + "\n" 
                                + generatedByEf6TempTableKitEndMsg
                                + "\n"
                                + selectCommandText;
                        }
                    }
                }
                command.CommandText = selectCommandText + currentCommandText;
            }
        }

        private System.Data.Entity.DbContext FindDbContextWithTempTable(IEnumerable<System.Data.Entity.DbContext> dbContexts)
        {
            foreach (var context in dbContexts)
            {
                if (context is IDbContextWithTempTable)
                {
                    return context;
                }
            }
            return null;
        }
    }
}