using EF6TempTableKit.DbContext;
using EF6TempTableKit.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EF6TempTableKit.Utilities
{
    /// <summary>
    /// Queries attached on a context are stored in a queue(FIFO) data structure. Why? Because last attached query typically has dependencies on previously attached queries.
    /// </summary>
    internal sealed class SqlFromTempTableDependenciesBuilder
    {
        private readonly Version _assemblyVersion;
        private readonly string _generatedByEf6TempTableKitStartMsg;
        private readonly string _generatedByEf6TempTableKitEndMsg;
        private readonly IDictionary<string, HashSet<string>> _tempOnTempDependencies;
        private readonly Queue<KeyValuePair<string, Query>> _tempSqlQueriesList;
        private HashSet<KeyValuePair<string, QueryType>> _alreadyAttachedTempTableQuery;

        internal SqlFromTempTableDependenciesBuilder(TempTableContainer tempTableContainer)
        {
            _tempOnTempDependencies = tempTableContainer.TempOnTempDependencies;
            _tempSqlQueriesList = tempTableContainer.TempSqlQueriesList;
            _alreadyAttachedTempTableQuery = new HashSet<KeyValuePair<string, QueryType>>();

            _assemblyVersion = typeof(EF6TempTableKitQueryInterceptor).Assembly.GetName().Version;
            _generatedByEf6TempTableKitStartMsg = $"/* Generated by EF6TempTableKit {_assemblyVersion} - START */";
            _generatedByEf6TempTableKitEndMsg = $"/* Generated by EF6TempTableKit {_assemblyVersion} - END*/";
        }

        public string BuildSqlForTempTables(string interceptedComandText)
        {
            var sqlStringBuilder = new StringBuilder();

            foreach (var tempSqlQuery in _tempSqlQueriesList)
            {
                var tempTableName = tempSqlQuery.Key;
                var tempTableNameWithBrackets = $"[{tempTableName}]";
                if (!tempSqlQuery.Value.IsExecuted && interceptedComandText.Contains(tempTableNameWithBrackets))
                {
                    var hasTempTableDependencies = _tempOnTempDependencies.ContainsKey(tempTableName);
                    if (hasTempTableDependencies)
                    {
                        foreach (var tempTableDependency in _tempOnTempDependencies[tempTableName])
                        {
                            var query = _tempSqlQueriesList.Single(t => t.Key == tempTableDependency).Value;
                            if (!query.IsExecuted)
                            {
                                AppendCommand(sqlStringBuilder, query.QueryString, tempTableDependency, query.QueryType);
                                query.IsExecuted = true;
                            }
                        }
                    }
                    if (!tempSqlQuery.Value.IsExecuted)
                    {
                        AppendCommand(sqlStringBuilder, tempSqlQuery.Value.QueryString, tempTableName, tempSqlQuery.Value.QueryType);
                        tempSqlQuery.Value.IsExecuted = true;
                    }
                }
            }

            return sqlStringBuilder.ToString();
        }

        private void AppendCommand(StringBuilder sqlStringBuilder, string sqlStringToAppend, string tempTableName, QueryType queryType)
        {
            var selectCommandTextFormat = "\n{0}\n{1}\n{2}\n";
            sqlStringBuilder.AppendFormat(selectCommandTextFormat, _generatedByEf6TempTableKitStartMsg, sqlStringToAppend, _generatedByEf6TempTableKitEndMsg);
            _alreadyAttachedTempTableQuery.Add(new KeyValuePair<string, QueryType>(tempTableName, queryType));
        }
    }
}
